### ISSUE TITLE
strok 0.12.0 don't collect data

### ISSUE THREAD

**Issue by younity-ENG** [isc-projects/stork#2]
hi

ive installed strok agent/server to monitor my kea dhcp server (1.8.0).
all components can communicate kea apps status is green, both dhcp4and ca.
i can see subnets, reserved IPs, but i can't see any statistics.
any idea how to fix this issue?

thanks

**Comment by tomaszmrugalski** [comment]
Hi,
Apologies for responding in such a delay. This github repository is a clone of the main repo at https://gitlab.isc.org/isc-projects/stork. You'll get much faster responses, as the Stork developers use it daily.

As for the specific issue, it has been investigated some time ago and the most likely explanation is that you need stat_cmds hook loaded. This is now documented here: https://stork.readthedocs.io/en/v0.16.0/install.html#installation-prerequisites

**Comment by tomaszmrugalski** [comment]
If this doesn't work for you, please open an issue at https://gitlab.isc.org/isc-projects/stork
